name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        mode:
          - tagged
          - legacy

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / ${{ matrix.mode }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Initialize required submodules
        run: git submodule update --init --depth 1 third_party/secp256k1-zkp third_party/nanobench reference/purify

      - name: Configure
        run: cmake --preset ${{ matrix.mode }}

      - name: Build
        run: cmake --build --preset ${{ matrix.mode }} --parallel

      - name: Test
        run: ctest --preset ${{ matrix.mode }}
